import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import { baseURL, endpoint } from "../constants";

type Item = {
  id: number;
  name: string;
  weight: number;
};
export const GameItem: Item[] = [];
export default function Home({ items }: { items: Item[] }) {
  const [selectedItem, setSelectedItem] = useState<any>(null);
  console.log(items);

  const _spin = async () => {
    let { data } = await axios({
      baseURL: baseURL,
      url: endpoint.spin,
      method: "POST",
    });
    return data as Item;
  };
  const onSelectItem = async () => {
    if (selectedItem !== null) {
      setSelectedItem(null);
      return;
    }

    let data = await _spin();
    if (data) {
      let _selectedItem = data.id;
      setSelectedItem(_selectedItem);
    }
  };

  return (
    <>
      <Head>
        <title>Lucky Wheel</title>
        <meta name="description" content="Generated by Spirity.JSC" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <div className="wheel-container">
          <div
            className={`wheel ${selectedItem !== null ? "spinning" : ""}`}
            style={
              {
                "--nb-item": items.length,
                "--selected-item": selectedItem,
              } as any
            }
            onClick={onSelectItem}
          >
            {items &&
              items.map((item, index: number) => (
                <div
                  className="wheel-item"
                  key={index}
                  style={{ "--item-nb": index } as any}
                >
                  {item.name}
                </div>
              ))}
          </div>
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  let { data } = await axios.get(baseURL + endpoint.get_reward);
  const start = {
    id: 0,
    name: "Start",
    weight: 0,
  };
  return {
    props: {
      items: [start, ...data],
    }, // will be passed to the page component as props
  };
}
