import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";

type Item = {
  name: string;
};
export const GameItem: Item[] = [];
export default function Home() {
  const [items, setItems] = useState<Item[]>(GameItem);

  const [selectedItem, setSelectedItem] = useState<any>(null);

  const [loading, setLoading] = useState<boolean>(false);
  const onSelectItem = () => {
    if (selectedItem !== null) {
      setSelectedItem(null);
      return;
    }
    setLoading(true);

    setTimeout(() => {
      const _selectedItem = Math.floor(Math.random() * items.length);
      setSelectedItem(_selectedItem);
      console.log(_selectedItem);
      setLoading(false);
    }, 150);
  };

  return (
    <>
      <Head>
        <title>Lucky Wheel</title>
        <meta name="description" content="Generated by Spirity.JSC" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <div className="wheel-container">
          <div
            className={`wheel ${selectedItem !== null ? "spinning" : ""}`}
            style={
              {
                "--nb-item": items.length,
                "--selected-item": selectedItem,
              } as any
            }
            onClick={onSelectItem}
          >
            {items &&
              items.map((item, index: number) => (
                <div
                  className="wheel-item"
                  key={index}
                  style={{ "--item-nb": index } as any}
                >
                  {item.name}
                </div>
              ))}
          </div>
        </div>
      </div>
    </>
  );
}
